Update sass linting
bitcrowd/frontend pull request #8
Opened 2016-10-18 14:11 UTC by planktonic

Fixes #2.

- Removes the sasslint files in favour of our current stylelint configs
- Creates an npm package

@weiland @pmeinhardt please take a look — I’ve stuck to the format you established in the `.eslintrc` files, hopefully all is correct. Works locally via `npm link`, yet to be published.

ESLinting the js here seemed overkill, but maybe you feel otherwise?

2016-10-19 08:20 UTC, pmeinhardt commented
How, cool! That will make using and also updating the config in our projects much easier 👍

2016-10-19 08:24 UTC, pmeinhardt requested changes

2016-10-19 08:24 UTC, pmeinhardt commented on linting/stylelint-config-bitcrowd/overrides.js
> +      "speak",
Maybe linting would be useful? Normally we don't add dangling commas.

2016-10-19 08:24 UTC, pmeinhardt commented on linting/stylelint-config-bitcrowd/overrides.js
> +      "speak",
…but I would also be okay with just removing the dangling now and - possibly - taking care of linting in a separate issue/PR.

2016-10-19 08:25 UTC, pmeinhardt requested changes

2016-10-19 08:25 UTC, pmeinhardt commented on linting/stylelint-config-bitcrowd/overrides.js
> +}
Also, there's a semicolon missing here.

2016-11-03 09:18 UTC, planktonic commented on linting/stylelint-config-bitcrowd/overrides.js
> +      "speak",
Hah! Perfect illustration that linting is indeed not overkill. On it 👍

2016-11-03 09:35 UTC, planktonic commented
@pmeinhardt I’ve added linting (`eslint-config-bitcrowd-base`) and fixed the linting errors reported.

2016-11-07 08:55 UTC, pmeinhardt approved these changes

2016-11-07 08:56 UTC, pmeinhardt commented
Cool, looks nice 😃

2016-11-07 09:41 UTC, merged